version: "3"

networks:
  network:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - "./realm-export.json:/opt/keycloak/data/import/keycloak-realm.json"
    ports:
      - "8080:8080"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./config/docker/collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      - network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - network

  prometheus:
    image: prom/prometheus
    ports:
      - "8083:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - network

  elasticsearch:
    image: elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
    networks:
      - network

  logstash:
    image: logstash:8.15.3
    volumes:
      - ./config/docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
#    environment:
#      - LS_JAVA_OPTS="-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - network

  kibana:
    image: kibana:8.15.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - network